### ISSUE TITLE
SmaCC_Elixir: Identifier misfires

### ISSUE THREAD

**Issue by mariari** [j-brant/SmaCC#32]
### EDIT

See my followup comment in this thread, I've identified the real issue, which is bracket_identifiers etc apply even when they should not.

This applies to the other `Identifier` rules in general.

To give another example:

![](https://pomf2.lain.la/f/pjw2mg.png)
```elixir
iex(ex-mariari@Gensokyo)4> with (5) <- 5 do 5 end
5
```

Fails to parse as I believe it's parsing as a `paren_identifier`

### Original Message

I'm unsure where the grammar goes wrong on this one.

Picture below is a few code examples.

![](https://pomf2.lain.la/f/d9y4hcgq.png)

```elixir
with %{} <- a,
     b <- height do
	5
end

with [a|_] <- a do
	5
end

with %{} <- a,
     b <- height do
	5
end

with [a, b] <- a,
     b <- height do
	5
end
```

Namely it has issues parsing the last one, where you have a list followed with a comma, this is true for both improper and normal lists, however structs and maps seem to parse fine.

**Comment by mariari** [comment]
After investigating a bit, I've found a possible explanation:

Let us look at the parser on the following examples both in `SmaCC` and in what Elixir itself gives us

```elixir
f[:a]

f [:a]
```

In SmaCC I see these are the same

![](https://pomf2.lain.la/f/m40aw36o.png)

These are expressions 4 and 5.

However when looking at it via `iex` and the `yrl` file I see the following

```elixir
iex(10)> quote do f[:a] end
{{:., [from_brackets: true], [Access, :get]}, [from_brackets: true],
 [{:f, [], Elixir}, :a]}
iex(11)> quote do f [:a] end
{:f, [], [[:a]]}
```

Which the first corresponds to their rule on `bracket_expr` while the last is not

```erlang
bracket_expr -> access_expr bracket_arg : build_access('$1', meta_with_from_brackets('$2')).
...
Erlang code .
...
build_access(Expr, {List, Meta}) ->
  {{'.', Meta, ['Elixir.Access', get]}, Meta, [Expr, List]}.

```

I believe this is relevant due to how the with parses, as with this finding, I got the following to parse

![](https://pomf2.lain.la/f/uv8eigsw.png)

**Comment by mariari** [comment]
To give a few more examples of identifiers improperly ignoring spaces:

```elixir
iex(mariari@Gensokyo)9> quote do f (1,2,3) end
** (SyntaxError) invalid syntax found on iex:9:12:
    error: unexpected parentheses. If you are making a function call, do not insert spaces between the function name and the opening parentheses. Syntax error before: '('
    │
  9 │ quote do f (1,2,3) end
    │            ^
    │
    └─ iex:9:12
    (iex 1.17.3) lib/iex/evaluator.ex:295: IEx.Evaluator.parse_eval_inspect/4
    (iex 1.17.3) lib/iex/evaluator.ex:187: IEx.Evaluator.loop/1
    (iex 1.17.3) lib/iex/evaluator.ex:32: IEx.Evaluator.init/5
    (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
iex(mariari@Gensokyo)9> quote do f(1,2,3) end
{:f, [], [1, 2, 3]}
```

![](https://pomf2.lain.la/f/6v56mrm2.png)
